
name: Build EyeLeo

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive 

      - name: Cache wxWidgets
        id: cache-wx
        uses: actions/cache@v4
        with:
          path: C:\Dev\wxWidgets-3.1.3
          key: wxwidgets-3.1.3-msvc2022-x64

      - name: Download and setup wxWidgets
        if: steps.cache-wx.outputs.cache-hit != 'true'
        run: |
          mkdir C:\Dev
          curl.exe -L -o C:\Dev\wxWidgets.zip https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.zip
          7z x C:\Dev\wxWidgets.zip -oC:\Dev\wxWidgets-3.1.3
        shell: cmd

      - name: Build wxWidgets
        if: steps.cache-wx.outputs.cache-hit != 'true'
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd C:\Dev\wxWidgets-3.1.3\build\msw
          nmake -f makefile.vc BUILD=release SHARED=0 RUNTIME_LIBS=static TARGET_CPU=X64
        shell: cmd

      - name: Configure and Build EyeLeo App
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set WXWIN=C:\Dev\wxWidgets-3.1.3\
          cmake -B windowsbuild .
          cmake --build windowsbuild --config Release
        shell: cmd

      - name: Upload compiled executable
        uses: actions/upload-artifact@v4
        with:
          name: EyeLeo-Windows-App
          path: windowsbuild/**/*.exe
