name: Build EyeLeo

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: windows-2022 # Используем актуальную версию ОС, так как 2019 удалена

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive 

      - name: Download and setup wxWidgets
        run: |
          mkdir C:\Dev
          curl.exe -L -o wxWidgets.zip https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.zip
          7z x wxWidgets.zip -oC:\Dev\wxWidgets-3.1.3
        shell: cmd
        
      - name: Build wxWidgets
        run: |
          # В VS 2022 изменился путь: теперь это Program Files, а не Program Files (x86)
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cd c:\Dev\wxWidgets-3.1.3\build\msw
          nmake -f makefile.vc BUILD=release SHARED=0 RUNTIME_LIBS=static TARGET_CPU=X64
        shell: cmd

      - name: Configure and Build EyeLeo
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          set WXWIN=c:\Dev\wxWidgets-3.1.3\
          cmake -B windowsbuild .
          cmake --build windowsbuild --config Release
        shell: cmd

      - name: Upload compiled executable
        uses: actions/upload-artifact@v4 # На 2026 год v4 (и новые версии v7) остаются актуальными стандартами
        with:
          name: EyeLeo-Windows-App
          path: windowsbuild/**/*.exe
